# Generated by Django 2.0.3 on 2020-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_meal_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('present_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('present_height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sex', models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male')], default='2', max_length=8)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'breakfast'), ('BIG', 'big'), ('SNACK', 'snack'), ('EXTRA', 'extra')], default='5', max_length=16),
        ),
    ]
