# Generated by Django 2.0.3 on 2020-06-21 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_auto_20200621_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='date of the meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_size',
            field=models.CharField(choices=[('BREAKFAST', 'breakfast'), ('BIG', 'big'), ('SNACK', 'snack'), ('EXTRA', 'extra')], default='1', max_length=16),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SNACK', 'snack'), ('EXTRA', 'extra')], default='1', max_length=16),
        ),
    ]
