# Generated by Django 2.0.3 on 2020-06-23 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20200621_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default', max_length=64)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SNACK SIZE', 'snack1'), ('SNACK SIZE', 'snack2'), ('EXTRA', 'extra')], default='1', max_length=64)),
                ('date', models.DateField(blank=True, default=datetime.date.today, help_text='date of consume')),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('ingredient', models.ManyToManyField(blank=True, related_name='ingredient', to='nutrition.Ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_size',
            field=models.CharField(choices=[('FULL SIZE', 'big'), ('SNACK SIZE', 'snack'), ('EXTRA', 'extra')], default='1', max_length=16),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SNACK SIZE', 'snack1'), ('SNACK SIZE', 'snack2'), ('EXTRA', 'extra')], default='1', max_length=16),
        ),
        migrations.AddField(
            model_name='consumed',
            name='mealingredient',
            field=models.ManyToManyField(blank=True, related_name='mealingredient', to='nutrition.MealIngredient'),
        ),
    ]
