# Generated by Django 2.0.3 on 2020-06-23 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_auto_20200623_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, default=datetime.date.today, help_text='date of the meal')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SNACK SIZE', 'snack1'), ('SNACK SIZE', 'snack2'), ('EXTRA', 'extra')], default='1', max_length=16)),
                ('quantity', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='nutrition.Ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='nutrition.Ingredient'),
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='nutrition.Ingredient'),
        ),
    ]
