# Generated by Django 2.0.3 on 2020-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_auto_20200623_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient10',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient3',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient4',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient5',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient6',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient7',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient8',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredient9',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity9',
            field=models.IntegerField(default=0),
        ),
    ]
