# Generated by Django 2.0.3 on 2020-06-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_auto_20200626_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
