# Generated by Django 2.0.3 on 2020-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_auto_20200626_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intake',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='intakes', to='nutrition.Food'),
        ),
    ]
