# Generated by Django 2.0.3 on 2020-06-28 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0020_auto_20200628_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='height',
        ),
        migrations.AddField(
            model_name='measurement',
            name='bmi',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=7),
        ),
        migrations.AddField(
            model_name='measurement',
            name='body_fat',
            field=models.DecimalField(decimal_places=1, default=99, max_digits=4),
        ),
        migrations.AddField(
            model_name='measurement',
            name='body_water',
            field=models.DecimalField(decimal_places=1, default=99, max_digits=4),
        ),
        migrations.AddField(
            model_name='measurement',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='date of consume'),
        ),
        migrations.AddField(
            model_name='personal',
            name='activity_level',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='planned_daily_deficit',
            field=models.IntegerField(default=0),
        ),
    ]
