# Generated by Django 2.0.3 on 2020-06-28 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0021_auto_20200628_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='date of consume'),
        ),
    ]
