# Generated by Django 2.0.3 on 2020-06-29 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0024_remove_personal_present_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='default', max_length=16)),
                ('date', models.DateField(blank=True, default=datetime.date.today, help_text='date of the meal')),
                ('meal_type', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('SNACK SIZE', 'snack1'), ('SNACK SIZE', 'snack2'), ('extra', 'extra')], default='1', max_length=16)),
                ('carb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calorie', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='needed_calorie',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='personal',
            name='needed_carb',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='personal',
            name='needed_fat',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='personal',
            name='needed_protein',
            field=models.IntegerField(default=30),
        ),
    ]
