# Generated by Django 2.0.3 on 2020-06-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0026_auto_20200629_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumed',
            name='mealingredient',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='mealingredient',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='MealItem',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bmi',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='body_fat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='body_water',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.DeleteModel(
            name='Consumed',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealIngredient',
        ),
    ]
