# Generated by Django 2.0.3 on 2020-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_auto_20200625_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='quantity1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='quantity9',
            field=models.IntegerField(default=0),
        ),
    ]
