# Generated by Django 2.0.3 on 2020-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_auto_20200625_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='total_caloria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='total_carb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='total_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='total_fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='total_protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
