# Generated by Django 2.0.3 on 2020-06-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_auto_20200626_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='nutritions',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='calorie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='carb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.AddField(
            model_name='portion',
            name='nutritions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='nutrition.Food'),
        ),
        migrations.AddField(
            model_name='intake',
            name='portions',
            field=models.ManyToManyField(blank=True, related_name='intakes', to='nutrition.Portion'),
        ),
    ]
