# Generated by Django 2.0.3 on 2020-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0018_auto_20200627_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumed',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('SNACK SIZE', 'snack1'), ('SNACK SIZE', 'snack2'), ('extra', 'extra')], default='1', max_length=64),
        ),
        migrations.AlterField(
            model_name='intake',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('SNACK SIZE', 'snack1'), ('SNACK SIZE', 'snack2'), ('extra', 'extra')], default='1', max_length=16),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_size',
            field=models.CharField(choices=[('FULL SIZE', 'big'), ('SNACK SIZE', 'snack'), ('extra', 'extra')], default='1', max_length=16),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('SNACK SIZE', 'snack1'), ('SNACK SIZE', 'snack2'), ('extra', 'extra')], default='1', max_length=16),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('SNACK SIZE', 'snack1'), ('SNACK SIZE', 'snack2'), ('extra', 'extra')], default='1', max_length=16),
        ),
    ]
