# Generated by Django 2.0.3 on 2020-06-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0022_auto_20200628_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='planned_daily_deficit',
            new_name='planned_daily_offset',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bmi',
            field=models.DecimalField(decimal_places=1, default=99, max_digits=7),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=99, max_digits=4),
        ),
    ]
