# Generated by Django 2.0.3 on 2020-06-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0023_auto_20200628_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='present_weight',
        ),
    ]
