# Generated by Django 2.0.3 on 2020-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0025_auto_20200629_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='calorie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='diary',
            name='carb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='diary',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='diary',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='diary',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='diary',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
